<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <Import Project="../Kni.props" />
  <ItemGroup>
    <PackageReference Include="Microsoft.JSInterop" Version="10.0.12" />
    <ProjectReference Include="Compatibility/xTile.Browser.csproj" />
    <ProjectReference Include="Compatibility/BmFont/BmFont.Browser.csproj" />
    <Compile Remove="Compatibility/**/bin/**;Compatibility/**/obj/**" />
  </ItemGroup>
</Project>
